#!/usr/bin/env ruby
# frozen_string_literal: true
# Run from repo root: ruby _scripts/generate_publication_counts.rb
# Updates _data/publication_counts.yml from _bibliography/papers.bib (same logic as the Jekyll plugin).

def published?(note_str)
  return false if note_str.nil? || note_str.to_s.strip.empty?
  n = note_str.to_s.downcase
  return false if n =~ /in\s+review/
  n =~ /published|accepted|in\s+press/
end

def type_category(raw_type)
  return nil if raw_type.nil? || raw_type.to_s.empty?
  t = raw_type.to_s.downcase
  return 'journal' if t == 'article'
  return 'conference' if t == 'inproceedings'
  return 'book_chapter' if %w[incollection inbook].include?(t)
  nil
end

root = File.expand_path('..', __dir__)
bib_path = File.join(root, '_bibliography', 'papers.bib')
unless File.file?(bib_path)
  warn "Bib not found: #{bib_path}"
  exit 1
end

published_journals = 0
published_conferences = 0
published_book_chapters = 0
in_review_journals = 0
in_review_conferences = 0
in_review_book_chapters = 0
current_type = nil
current_note = nil
in_note = false
note_buffer = ''

File.foreach(bib_path, encoding: 'UTF-8') do |line|
  if line =~ /\A\s*@(\w+)\s*\{/
    if current_type
      note_str = (current_note || note_buffer).to_s.strip
      category = type_category(current_type)
      if category
        if published?(note_str)
          case category
          when 'journal' then published_journals += 1
          when 'conference' then published_conferences += 1
          when 'book_chapter' then published_book_chapters += 1
          end
        else
          case category
          when 'journal' then in_review_journals += 1
          when 'conference' then in_review_conferences += 1
          when 'book_chapter' then in_review_book_chapters += 1
          end
        end
      end
    end
    raw_type = Regexp.last_match(1)
    current_type = raw_type&.downcase
    current_note = nil
    in_note = false
    note_buffer = ''
    next
  end

  if line =~ /\bnote\s*=\s*\{?\s*(.*)/
    in_note = true
    rest = Regexp.last_match(1)
    if rest =~ /\}(?:\s*,?\s*)?\s*$/
      current_note = rest.sub(/\}(?:\s*,?\s*)?\s*$/, '').strip
      in_note = false
    else
      note_buffer = rest.to_s.strip
    end
    next
  end

  if in_note
    if line =~ /\}\s*,?\s*$/
      note_buffer += ' ' + line.sub(/\}\s*,?\s*$/, '').strip
      current_note = note_buffer
      in_note = false
      note_buffer = ''
    else
      note_buffer += ' ' + line.strip
    end
  end
end

if current_type
  note_str = (current_note || note_buffer).to_s.strip
  category = type_category(current_type)
  if category
    if published?(note_str)
      case category
      when 'journal' then published_journals += 1
      when 'conference' then published_conferences += 1
      when 'book_chapter' then published_book_chapters += 1
      end
    else
      case category
      when 'journal' then in_review_journals += 1
      when 'conference' then in_review_conferences += 1
      when 'book_chapter' then in_review_book_chapters += 1
      end
    end
  end
end

published_total = published_journals + published_conferences + published_book_chapters
in_review_total = in_review_journals + in_review_conferences + in_review_book_chapters

data = {
  'published_total' => published_total,
  'published_journals' => published_journals,
  'published_conferences' => published_conferences,
  'published_book_chapters' => published_book_chapters,
  'in_review_total' => in_review_total,
  'in_review_journals' => in_review_journals,
  'in_review_conferences' => in_review_conferences,
  'in_review_book_chapters' => in_review_book_chapters,
  'journals' => published_journals + in_review_journals,
  'conferences' => published_conferences + in_review_conferences,
  'book_chapters' => published_book_chapters + in_review_book_chapters
}

out_path = File.join(root, '_data', 'publication_counts.yml')
File.write(out_path, <<~YAML)
  # Generated by _scripts/generate_publication_counts.rb from _bibliography/papers.bib
  # Run: ruby _scripts/generate_publication_counts.rb

  published_total: #{data['published_total']}
  published_journals: #{data['published_journals']}
  published_conferences: #{data['published_conferences']}
  published_book_chapters: #{data['published_book_chapters']}
  in_review_total: #{data['in_review_total']}
  in_review_journals: #{data['in_review_journals']}
  in_review_conferences: #{data['in_review_conferences']}
  in_review_book_chapters: #{data['in_review_book_chapters']}
  journals: #{data['journals']}
  conferences: #{data['conferences']}
  book_chapters: #{data['book_chapters']}
YAML

puts "Wrote #{out_path}: published=#{published_total} (j=#{published_journals} c=#{published_conferences} b=#{published_book_chapters}), in_review=#{in_review_total} (j=#{in_review_journals} c=#{in_review_conferences} b=#{in_review_book_chapters})"
